services:
    sygefor_trainee.form.type.trainee:
            class: Sygefor\Bundle\TraineeBundle\Form\BaseTraineeType
            arguments:
                - "@Sygefor_core.access_right_registry"
            tags:
                - { name: form.type, alias: trainee }

    sygefor_trainee.form.type.traineemailingtemplate:
        class: Sygefor\Bundle\TraineeBundle\Form\EmailTemplateVocabularyType
        arguments:
            - "@security.context"
            - "@Sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: emailtemplatevocabulary }