services:
    sygefor_trainee.trainee.orm.listener:
        class: Sygefor\Bundle\TraineeBundle\Listener\TraineeListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # user provider
    sygefor_trainee.user_provider:
        class: Sygefor\Bundle\TraineeBundle\Entity\TraineeRepository
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:
            - 'Sygefor\Bundle\TraineeBundle\Entity\AbstractTrainee'

    #trainee menu
    sygefor_trainee.configure_menu_listener:
        class: Sygefor\Bundle\TraineeBundle\EventListener\ConfigureMenuListener
        arguments:
            - "@security.context"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }
