parameters:
    sygefor_trainee.taxonomy.group: "Public"

services:
    sygefor_trainee.vocabulary_email_template:
        class:        Sygefor\Bundle\TraineeBundle\Entity\Term\EmailTemplate
        tags:
            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_trainee.taxonomy.group%" }

    sygefor_trainee.vocabulary_public_type:
        class:        Sygefor\Bundle\TraineeBundle\Entity\Term\PublicType
        tags:
            - { name: sygefor_core.vocabulary_provider,  group: "%sygefor_trainee.taxonomy.group%" }

    sygefor_trainee.vocabulary_disciplinary:
        class:        Sygefor\Bundle\TraineeBundle\Entity\Term\Disciplinary
        tags:
            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_trainee.taxonomy.group%" }
