services:

    #trainee voters
    sygefor_trainee.rights.trainee.own.view:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\OwnTraineeViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.own.create:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\OwnTraineeCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.own.update:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\OwnTraineeUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.own.delete:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\OwnTraineeDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }

    sygefor_trainee.rights.trainee.all.view:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\AllTraineeViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.all.create:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\AllTraineeCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.all.update:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\AllTraineeUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }
    sygefor_trainee.rights.trainee.all.delete:
        class: Sygefor\Bundle\TraineeBundle\Security\Authorization\AccessRight\AllTraineeDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Stagiaires" }