services:
    sygefor_training.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.training"]

    sygefor_training.semestered.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.semestered_training"]

    sygefor_training.session.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.session"]

    # elastica transformer
    sygefor_training.session.elastica.transformer:
        class: Sygefor\Bundle\TrainingBundle\Transformer\SessionToElasticaTransformer
        arguments: ["@service_container"]
        calls:
            - [setPropertyAccessor, ["@fos_elastica.property_accessor"]]

    #provider for semestered training
    sygefor_training.elastica_provider.semestered_training:
        class: Sygefor\Bundle\TrainingBundle\Providers\SemesteredTrainingProvider
        arguments:
            - "@fos_elastica.object_persister.sygefor3.semestered_training"
            - "@fos_elastica.indexable"
            - "@doctrine"
        tags:
            - { name: fos_elastica.provider, index: sygefor3, type: semestered_training }

    sygefor_participation.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.participation"]