services:
    sygefor_training.form.type.training:
        class:      Sygefor\Bundle\TrainingBundle\Form\TrainingType
        arguments:
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: trainingtype }

    sygefor_training.form.type.placetype:
        class: Sygefor\Bundle\TrainingBundle\Form\PlaceType
        arguments:
            - "@security.context"
        tags:
            - { name: form.type, alias: placetype }

    sygefor_training.form.type.publictype:
        class: Sygefor\Bundle\TrainingBundle\Form\PublicTypeType
        arguments:
            - "@security.context"
        tags:
            - { name: form.type, alias: publictype }

    sygefor_training.form.type.training_category_type:
            class: Sygefor\Bundle\TrainingBundle\Form\TrainingCategoryType
            arguments:
                - "@security.context"
                - "@sygefor_training.type.registry"
            tags:
                - { name: form.type, alias: trainingcategoryvocabulary }

    sygefor_training.form.type.supervisor_type:
            class: Sygefor\Bundle\TrainingBundle\Form\SupervisorType
            arguments:
                - "@security.context"
            tags:
                - { name: form.type, alias: supervisorvocabulary }