services:
    # training types registry
    sygefor_training.type.registry:
        class: Sygefor\Bundle\TrainingBundle\Registry\TrainingTypeRegistry
        arguments: [null] # all services with tag "sygefor_training.type are inserted here by TrainingTypeRegistryPass

    # doctrine event subscriber
    sygefor_training.training.listener:
        class: Sygefor\Bundle\TrainingBundle\Listener\TrainingListener
        arguments:
            - "@sygefor_training.type.registry"
        tags:
            - { name: doctrine.event_subscriber }
    sygefor_training.session.listener:
        class: Sygefor\Bundle\TrainingBundle\Listener\SessionListener
        tags:
            - { name: doctrine.event_subscriber }

    #event listener
    sygefor_training.semestered_training_listener:
        class: Sygefor\Bundle\TrainingBundle\Listener\SemesteredTrainingListener
        arguments:
            - "@fos_elastica.object_persister.sygefor3.semestered_training"
            - "@fos_elastica.indexable"
            - "@fos_elastica.index.sygefor3.semestered_training"
        tags:
            - { name: doctrine.event_subscriber, connection: default  }
            - { name: fos_elastica.listener }

    sygefor_trainer.participation.orm.listener:
        class: Sygefor\Bundle\TrainingBundle\Listener\TrainerParticipationListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # batch operation
    sygefor_training.batch.session_registration_change:
          class: Sygefor\Bundle\TrainingBundle\BatchOperations\SessionRegistrationChangeBatchOperation
          arguments:
              - "@doctrine.orm.entity_manager"
          calls:
              - [ setContainer, [ "@service_container" ] ]
          tags:
              - {name: sygefor_core.batch_operation_provider}

    # serializer
    sygefor_training.serializer.training.event_subscriber:
        class: Sygefor\Bundle\TrainingBundle\Serializer\EventSubscriber\TrainingEventSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    sygefor_training.serializer.session.event_subscriber:
        class: Sygefor\Bundle\TrainingBundle\Serializer\EventSubscriber\SessionEventSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: jms_serializer.event_subscriber }

    # menu
    sygefor_training.configure_menu_listener:
        class: Sygefor\Bundle\TrainingBundle\EventListener\ConfigureMenuListener
        arguments:
            - "@security.context"
            - "@router"
            - "@sygefor_training.type.registry"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }
