services:
    # own training rights
    sygefor_training.rights.training.own.view:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\OwnTrainingViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.own.create:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\OwnTrainingCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.own.update:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\OwnTrainingUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.own.delete:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\OwnTrainingDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    # all training rights
    sygefor_training.rights.training.all.view:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\AllTrainingViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.all.create:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\AllTrainingCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.all.update:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\AllTrainingUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }

    sygefor_training.rights.training.all.delete:
        class:        Sygefor\Bundle\TrainingBundle\Security\Authorization\AccessRight\AllTrainingDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Formations" }