parameters:
    sygefor_inscription.taxonomy.group: "Inscription"

services:
    sygefor_inscription.vocabulary_inscription_status:
            class:        Sygefor\Bundle\InscriptionBundle\Entity\Term\InscriptionStatus
            tags:
                - { name: sygefor_core.vocabulary_provider, group: "%sygefor_inscription.taxonomy.group%" }

    sygefor_inscription.vocabulary_presence_status:
        class:        Sygefor\Bundle\InscriptionBundle\Entity\Term\PresenceStatus
        tags:
            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_inscription.taxonomy.group%" }
