services:
    # batch operations registry
    sygefor_list.batch_operation_registry: # todo blaise : rename to sygefor_list.batch_registry
        class:  Sygefor\Bundle\ListBundle\BatchOperation\BatchOperationRegistry

    # batch operations decorators
    sygefor_list.batch.convert_type:
        class: Sygefor\Bundle\ListBundle\BatchOperations\ConvertTypeBatchOperation
        abstract: true
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
            - @sygefor_training.type.registry
            - @sygefor_training.semestered.search
            - @fos_elastica.client
            - @fos_elastica.index
            - @fos_elastica.index.sygefor3.semestered_training

    # batch operations decorators
    sygefor_list.batch.csv:
        class: Sygefor\Bundle\ListBundle\BatchOperations\CSVBatchOperation
        abstract: true
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context

    sygefor_list.batch.publipost:
        class: Sygefor\Bundle\ListBundle\BatchOperations\MailingBatchOperation
        abstract: true
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
        calls:
            - [ setContainer, [ @service_container ] ]

    sygefor_list.batch.pdf:
        class: Sygefor\Bundle\ListBundle\BatchOperations\PDFBatchOperation
        abstract: true
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_snappy.pdf
            - @templating
            - @security.context
            - @kernel

    sygefor_list.batch.email:
          class: Sygefor\Bundle\ListBundle\BatchOperations\EmailingBatchOperation
          arguments:
              - @doctrine.orm.entity_manager
              - @security.context
          calls:
              - [ setContainer, [ @service_container ] ]
          tags:
              - {name: sygefor_list.batch_operation_provider}

    # property accessor factory
    sygefor_list.human_readable_property_accessor_factory:
        class: Sygefor\Bundle\ListBundle\HumanReadablePropertyAccessor\HumanReadablePropertyAccessorFactory
        arguments:
            - @doctrine.orm.entity_manager
        # setTermCatalog called by the compilation

    #forms
    #form for publipost templates taxonomy
    sygefor_trainee.form.type.publipost_template_vocabulary:
        class: Sygefor\Bundle\ListBundle\Form\Type\PublipostTemplateVocabularyType
        arguments:
            - @security.context
            - @Sygefor_user.access_right_registry
            - @Doctrine.orm.entity_manager
        calls:
            - [ setHRPAFactory, [ @sygefor_list.human_readable_property_accessor_factory ] ]
        tags:
            - { name: form.type, alias: publiposttemplatevocabulary }
    #taxonomy terms
    sygefor_list.publipost_template:
        class: Sygefor\Bundle\ListBundle\Entity\Term\PublipostTemplate
        tags:
            - { name: sygefor_taxonomy.vocabulary_provider, group: "%sygefor_training.taxonomy.group%" }
    #elastica
    sygefor_email.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: [@fos_elastica.index.sygefor3.email]