sygefor_lhoe:
    resource: "@SygeforLheoBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_core:
    resource: "@SygeforCoreBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_list:
    resource: "@SygeforListBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_taxonomy:
    resource: "@SygeforTaxonomyBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_training:
    resource: "@SygeforTrainingBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_trainee:
    resource: "@SygeforTraineeBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_trainer:
    resource: "@SygeforTrainerBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_user:
    resource: "@SygeforUserBundle/Controller/"
    type:     annotation
    prefix:   /admin

sygefor_api:
    resource: "@SygeforApiBundle/Controller/"
    type:     annotation
    prefix:   /

sygefor_activity_report:
    resource: "@SygeforActivityReportBundle/Controller/"
    type:     annotation
    prefix:   /

shibboleth_logout:
    path:   /api/shibboleth/logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
