security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        trainees:
            id: sygefor_api.account_repository
        shibboleth:
            id: sygefor_api.shibboleth.user_provider

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        AppBundle\Entity\Trainee\Trainee: sha512

    firewalls:
        # ---
        # Back FOS User
        # ---
        main:
            host: "%back_host%"
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            remember_me:
                key:      "%secret%"
                lifetime: 86400 # in seconds
                path:     /
                domain:   ~
            logout:       true
            anonymous:    true
            switch_user:  true

        # ---
        # OAuth authentication
        # ---
#        oauth_authorize:
#            host: "%front_host%"
#            pattern:    ^/oauth/v2/auth
#            form_login:
#                provider: trainees
#                check_path: api.oauth.auth_login_check
#                login_path: api.oauth.auth_login
#            anonymous: true
#        oauth_token:
#            pattern:    ^/oauth/v2/token
#            security:   false

        # ---
        # Front office
        # ---
        front:
            host: "%front_host%"
            pattern: ^/
            shibboleth: ~
            provider: shibboleth
            form_login:
                provider: trainees
                login_path: "/page/login"
                csrf_provider: form.csrf_provider
            logout:
                path: /account/logout
                target: /
            anonymous: ~

        # ---
        # API
        # ---
        api:
            host: "%front_host%"
            pattern:    ^/api
#            fos_oauth:  true
            stateless:  true
            anonymous:  ~

    access_control:
        # Back
        - { host: "%back_host%", path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/material/[^/]+/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: "%back_host%", path: ^/, role: IS_AUTHENTICATED_FULLY }

        # Front
        - { host: "%front_host%", path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: "%front_host%", path: ^/account/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: "%front_host%", path: ^/account, role: IS_AUTHENTICATED_FULLY }
        - { host: "%front_host%", path: ^/training/inscription, role: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_TRAINEE:       ROLE_USER
        ROLE_COFO:          ROLE_USER
        ROLE_EDITEUR:       ROLE_USER
        ROLE_GESTIONNAIRE:  ROLE_USER
        ROLE_ADMIN:         [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

# OAuth Configuration
fos_oauth_server:
    db_driver:           orm
    client_class:        Sygefor\Bundle\ApiBundle\Entity\Client
    access_token_class:  Sygefor\Bundle\ApiBundle\Entity\AccessToken
    refresh_token_class: Sygefor\Bundle\ApiBundle\Entity\RefreshToken
    auth_code_class:     Sygefor\Bundle\ApiBundle\Entity\AuthCode
    service:
        user_provider: sygefor_api.account_repository
#        options:
#            access_token_lifetime: 90
#        options:
#            supported_scopes: user

#Shibboleth
shibboleth:
    handler_path: /Shibboleth.sso
    secured_handler: "%shibboleth_secured_handler%"
    session_initiator_path: /Login
    username_attribute: mail
    use_headers: true
    attribute_definitions:
        targeted-id:
            header: targeted-id
        persistent-id:
            header: persistent-id
        eppn:
            header: eppn
        givenName:
            header: givenName
        sn:
            header: sn
        mail:
            header: mail
        telephoneNumber:
            header: telephoneNumber
        ou:
            header: ou
# CORS
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []