services:
    sygefor_trainer.rights.trainer.own.view:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\OwnTrainerViewAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.own.create:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\OwnTrainerCreateAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.own.update:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\OwnTrainerUpdateAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.own.delete:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\OwnTrainerDeleteAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }

    sygefor_trainer.rights.trainer.all.view:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\AllTrainerViewAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.all.create:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\AllTrainerCreateAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.all.update:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\AllTrainerUpdateAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }
    sygefor_trainer.rights.trainer.all.delete:
        class: Sygefor\Bundle\TrainerBundle\Security\Authorization\AccessRight\AllTrainerDeleteAccessRights
        tags:
            - { name: sygefor_core.right_provider, group: "Formateurs" }