parameters:
    sygefor_taxonomy.vocabulary_registry.class: Sygefor\Bundle\TaxonomyBundle\Vocabulary\VocabularyRegistry

services:
    sygefor_taxonomy.vocabulary_registry:
        class: %sygefor_taxonomy.vocabulary_registry.class%

    # vocabularies
    sygefor_taxonomy.rights.vocabulary.all:
        class:        Sygefor\Bundle\TaxonomyBundle\Security\Authorization\AccessRight\AllOrganizationVocabularyAccessRight
        tags:
            - { name: sygefor_user.right_provider, group: "Vocabulaires" }
    sygefor_taxonomy.rights.vocabulary.own:
        class:        Sygefor\Bundle\TaxonomyBundle\Security\Authorization\AccessRight\OwnOrganizationVocabularyAccessRight
        tags:
            - { name: sygefor_user.right_provider, group: "Vocabulaires" }
    sygefor_taxonomy.rights.vocabulary.national:
        class:        Sygefor\Bundle\TaxonomyBundle\Security\Authorization\AccessRight\NationalVocabularyAccessRight
        tags:
            - { name: sygefor_user.right_provider, group: "Vocabulaires" }

    sygefor_taxonomy.configure_menu_listener:
        class: Sygefor\Bundle\TaxonomyBundle\EventListener\ConfigureMenuListener
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }

    # orm
    sygefor_taxonomy.tree_trait_listener:
        class: Sygefor\Bundle\TaxonomyBundle\Listener\TreeTraitListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # request
    sygefor_taxonomy.vocabulary_param_converter:
        class:  Sygefor\Bundle\TaxonomyBundle\Request\ParamConverter\VocabularyParamConverter
        arguments:
            - @sygefor_taxonomy.vocabulary_registry
        tags:
            - { name: request.param_converter, priority: -2, converter: sygefor_taxonomy.vocabulary }

    # forms
    sygefor_taxonomy.form.type.entity_tags:
        class: Sygefor\Bundle\TaxonomyBundle\Form\Type\EntityTagsType
        arguments: [@doctrine]
        tags:
            - { name: form.type, alias: entity_tags }
    sygefor_taxonomy.form.type.vocabulary:
        class: Sygefor\Bundle\TaxonomyBundle\Form\Type\VocabularyType
        arguments:
            - @security.context
            - @Sygefor_user.access_right_registry
            - @Doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: vocabulary }

    sygefor_taxonomy.form.type.institution_vocabulary:
        class: Sygefor\Bundle\TaxonomyBundle\Form\Type\InstitutionType
        tags:
            - { name: form.type, alias: institution }
        parent: sygefor_taxonomy.form.type.vocabulary

    sygefor_taxonomy.form.type.place_vocabulary:
        class: Sygefor\Bundle\TaxonomyBundle\Form\Type\PlaceType
        tags:
            - { name: form.type, alias: place }
        parent: sygefor_taxonomy.form.type.vocabulary
