services:
    sygefor_elastica_update.elastica_mapping_provider:
        class: Sygefor\Bundle\ElasticaUpdateBundle\MappingProvider\MappingProvider
        arguments:
            - '' #argument is set during configuration
            - '@service_container'
        #calls:
        #    - [setEntityManager, [@doctrine.orm.entity_manager]]

    #@todo hm: fix config pass before uncommenting service
    sygefor_elastica_update.cascade_update_listener:
        class: Sygefor\Bundle\ElasticaUpdateBundle\Listener\ElasticaCascadeUpdateListener
        arguments:
            - @kernel
            - @sygefor_elastica_update.elastica_mapping_provider
        tags:
            - { name: doctrine.event_subscriber, priority: -2 }
            - { name: fos_elastica.listener }
