services:
    # AccessRightRegistry
    sygefor_user.access_right_registry:
        class: Sygefor\Bundle\UserBundle\AccessRight\AccessRightRegistry
        arguments:
          - @service_container

    sygefor_user.rights.user.own:
        class:        Sygefor\Bundle\UserBundle\Security\Authorization\AccessRight\OwnOrganizationUserAccessRight
        tags:
            - { name: sygefor_user.right_provider, group: "Utilisateurs" }
    sygefor_user.rights.user.all:
        class:        Sygefor\Bundle\UserBundle\Security\Authorization\AccessRight\AllOrganizationUserAccessRight
        tags:
            - { name: sygefor_user.right_provider, group: "Utilisateurs" }

    # AccessRightVoter
    sygefor_user.access_right_voter:
        class: Sygefor\Bundle\UserBundle\Security\Authorization\Voter\AccessRightVoter
        public: false
        arguments:
            - @sygefor_user.access_right_registry
            - @doctrine.orm.entity_manager
        tags:
            - { name:security.voter }

    # AdminVoter
    sygefor_user.admin_voter:
        class: Sygefor\Bundle\UserBundle\Security\Authorization\Voter\AdminVoter
        public: false
        tags:
            - { name:security.voter }

    sygefor_user.configure_menu_listener:
        class: Sygefor\Bundle\UserBundle\EventListener\ConfigureMenuListener
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }

    #serialization
    sygefor_user.serializer.access_rights.event_subscriber:
        class: Sygefor\Bundle\UserBundle\Serializer\EventSubscriber\AccessRightsEventSubscriber
        arguments:
            - @security.context
        tags:
            - { name: jms_serializer.event_subscriber }

    #forms
    sygefor_user.form.type.access_rights:
        class:      Sygefor\Bundle\UserBundle\Form\AccessRightType
        arguments:
            - @sygefor_user.access_right_registry
        tags:
            - { name: form.type, alias: access_rights }

    sygefor_user.form.type.user:
        class:      Sygefor\Bundle\UserBundle\Form\UserType
        arguments:
            - "@sygefor_user.access_right_registry"
        tags:
            - { name: form.type, alias: user }
