parameters:
    sygefor_activity_report.builder_factory.class: Sygefor\Bundle\ActivityReportBundle\Service\ActivityReportBuilderFactory
    sygefor_excel_writer.class: Sygefor\Bundle\ActivityReportBundle\Service\ExcelWriter
    sygefor_xls_paginer.class: Sygefor\Bundle\ActivityReportBundle\Service\XlsExportPaginer

services:
    sygefor_activity_report.builder_factory:
        class: "%sygefor_activity_report.builder_factory.class%"
        arguments: ["@fos_elastica.index", "@doctrine.orm.entity_manager"]
    sygefor_activity_report.configure_menu_listener:
        class: Sygefor\Bundle\ActivityReportBundle\EventListener\ConfigureMenuListener
        arguments:
                    - "@security.context"
                    - "@router"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }
    sygefor_excel_writer:
        class: "%sygefor_excel_writer.class%"
    sygefor_xls_paginer:
        class: "%sygefor_xls_paginer.class%"
