parameters:
    sygefor_activity_report.builder_factory.class: Sygefor\Bundle\ActivityReportBundle\Service\ActivityReportBuilderFactory

services:
    sygefor_activity_report.builder_factory:
        class: %sygefor_activity_report.builder_factory.class%
        arguments: [@fos_elastica.index, @doctrine.orm.entity_manager]
    sygefor_activity_report.configure_menu_listener:
        class: Sygefor\Bundle\ActivityReportBundle\EventListener\ConfigureMenuListener
        arguments:
                    - @security.context
                    - @router
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }
