services:
    # taxonomy form types
    sygefor_mycompany.form.type.menu_item_type:
        class: Sygefor\Bundle\MyCompanyBundle\Form\MenuItemType
        arguments:
            - "@security.context"
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: menuitemtype }

    sygefor_mycompany.form.type.trainee:
        class: Sygefor\Bundle\MyCompanyBundle\Form\TraineeType
        arguments:
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: traineetype }

    # training forms
    sygefor_mycompany.form.type.internship:
        class:      Sygefor\Bundle\MyCompanyBundle\Form\InternshipType
        arguments:
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: internshiptype }

    sygefor_mycompany.form.type.meeting:
        class:      Sygefor\Bundle\MyCompanyBundle\Form\MeetingType
        arguments:
            - "@sygefor_core.access_right_registry"
            - 'Sygefor\Bundle\MyCompanyBundle\Entity\Session'
        tags:
            - { name: form.type, alias: meetingtype }

    sygefor_mycompany.form.type.long_training:
        class:      Sygefor\Bundle\MyCompanyBundle\Form\LongTrainingType
        arguments:
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: longtrainingtype }

    sygefor_mycompany.form.type.institution:
        class: Sygefor\Bundle\MyCompanyBundle\Form\InstitutionType
        arguments:
            - "@sygefor_core.access_right_registry"
        tags:
            - { name: form.type, alias: institutiontype }