services:
    # IMPORTANT GO YO TRAINING.CONFIG.JS ADD YOUR TRAINING TYPES TOO (@ MyCompanyBundle/Resources/public/ng/training/training/training.config.js)
    sygefor_mycompany.type.internship:
        class: Sygefor\Bundle\MyCompanyBundle\Entity\Internship
        tags:
            - { name: sygefor_training.type }
    sygefor_mycompany.type.long_training:
        class: Sygefor\Bundle\MyCompanyBundle\Entity\LongTraining
        tags:
            - { name: sygefor_training.type }
    sygefor_mycompany.type.meeting:
        class: Sygefor\Bundle\MyCompanyBundle\Entity\Meeting
        tags:
            - { name: sygefor_training.type }