services:
    #elastica
    sygefor_institution.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.institution"]

    #institution menu
    sygefor_institution.configure_menu_listener:
        class: Sygefor\Bundle\InstitutionBundle\EventListener\ConfigureMenuListener
        arguments:
                    - "@security.context"
                    - "@router"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }