services:
    # Own voters
    sygefor_institution.rights.institution.own.view:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\OwnInstitutionViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.own.create:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\OwnInstitutionCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.own.update:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\OwnInstitutionUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.own.delete:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\OwnInstitutionDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    # All voters 
    sygefor_institution.rights.institution.all.view:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\AllInstitutionViewAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.all.create:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\AllInstitutionCreateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.all.update:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\AllInstitutionUpdateAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }
    sygefor_institution.rights.institution.all.delete:
        class: Sygefor\Bundle\InstitutionBundle\Security\Authorization\AccessRight\AllInstitutionDeleteAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Etablissements" }